version: '3'
services:
  web:
    image: nginx:1.17.8-alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert-key/localhost.pem:/etc/certs/localhost.pem
      - ./nginx/cert-key/localhost-key.pem:/etc/certs/localhost-key.pem
  php-fpm:
    build: ./php-fpm
    ports:
      - 9000:9000
      - 8001:8001
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    working_dir: /var/www/html/laravel
    volumes:
      - ../:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=gizumohack
    volumes:
      - ./data-mysql:/var/lib/mysql
    container_name: mysql57
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - web
    privileged: true
    container_name: selenium
